runtime: python
env: flex
entrypoint: gunicorn -b :$PORT ingestapp:app -t 600
service: flights
manual_scaling:
  instances: 1

runtime_config:
    python_version: 3
#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: 2017_2018_flights
#[END env]

handlers:
- url: /ingest
  script: ingestapp.app

- url: /.*
  script: ingestapp.app
